# Generated by Django 5.1.3 on 2024-11-25 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffmodel',
            name='photo',
            field=models.ImageField(blank=True, default='avatar/userPhoto.jpg', upload_to='staff_photos'),
        ),
    ]
